### ISSUE TITLE
cant get it to work

### ISSUE THREAD

**Issue by ob7** [VxMxPx/pxtoem#1]
Ive cloned the repo...lets say I want to convert 1200px to em -  I run
./pxtoem.py 1200px
it gives error
pxtoem: error: argument base: invalid int value: '1200px'

You didnt give any examples so I'm not sure what I should be typing to do the conversion.  You should update the readme with examples please.

**Comment by VxMxPx** [comment]
Updated.
Please do pull again, because a bug was fixed in the process.
